[project]
name = "handson-mcp-server"
version = "0.1.0"
description = "Create an MCP server and use it from coding tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.24.0",
]

[tool.uv.workspace]
members = [
    "handson-1",
]
